version: '3.8'

services:
  backend:
    # Si le VPS construit l'image localement, laissez "build: ./backend"
    # Sinon, si tiré du Docker Hub, utilisez "image: seerm/nextrole-backend:latest"
    build: ./backend
    container_name: nextrole_backend_prod
    # Pas besoin d'exposer le port backend publiquement, NGINX va router vers lui via le réseau Docker (port 3000)
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - BASE_AVATAR_URL=${BASE_AVATAR_URL}
    restart: always

  frontend:
    # build local ou "image: seerm/nextrole-frontend:latest"
    build:
      context: ./frontend
      # ARG injecté lors du build de l'image de production sur le VPS
      args:
        - VITE_BACKEND_URI=${VITE_BACKEND_URI}
    container_name: nextrole_frontend_prod
    ports:
      # NGINX (sur le VPS directement) va forwarder sur ce port 5173
      - "127.0.0.1:5173:80"
    depends_on:
      - backend
    restart: always
