version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nextrole_backend
    ports:
      - "3000:3000"
    environment:
      # L'URL Frontend qui aura accès au CORS
      - FRONTEND_URL=http://localhost:5173
      # Configuration MongoDB (ex: host.docker.internal si mongo en local sur le host)
      - DB_HOST=host.docker.internal
      - DB_PORT=27017
      - DB_NAME=nextroute
      - JWT_SECRET=9de87a20b73617ba4c0a89bb1637980932ce6730547bb9f82c3f60a0a10fa1a312511f5ccad75e96cbeb80ea35f66d048975b5f2396e7ae3f9e03a45facd4328
      - SALT_ROUNDS=10
      - BASE_AVATAR_URL=https://api.dicebear.com/9.x/avataaars-neutral/svg?seed=
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        # En local, le frontend appelle le backend via localhost:3000
        - VITE_BACKEND_URI=http://localhost:3000
    container_name: nextrole_frontend
    ports:
      # Mappe le port Nginx (80) sur le 5173 du host pour simuler le dev
      - "5173:80"
    depends_on:
      - backend
    restart: always
