server {
    listen 80;
    server_name nextrole.maashrees.fr;

    # Gérer la route de l'API (redirige vers le container backend port 3000)
    location /api/ {
        # Le backend est accessible via localhost:3000 sur le VPS
        proxy_pass http://127.0.0.1:3005/;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Sécurité des headers proxy
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Gérer la route principale (redirige vers le container frontend port 5173 qui expose l'app react)
    location / {
        proxy_pass http://127.0.0.1:5174;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
